# Generated by Django 4.2.6 on 2026-04-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tradingview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectorsymbol",
            name="company_name",
            field=models.CharField(max_length=100),
        ),
    ]
