# Generated by Django 4.2.6 on 2026-04-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tradingview", "0002_alter_sectorsymbol_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sector",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="sectorsymbol",
            name="symbol",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
