# Generated by Django 4.2.6 on 2026-04-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tradingview", "0003_alter_sector_name_alter_sectorsymbol_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectorsymbol",
            name="symbol",
            field=models.CharField(max_length=50),
        ),
    ]
