# Generated by Django 4.2.6 on 2024-11-09 10:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeAbout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=40, unique=True, verbose_name="Title"),
                ),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Home About Content",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="HomePageService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=40, unique=True, verbose_name="Title"),
                ),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Home Service Management",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Horoscope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, unique=True, verbose_name="Name"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Horoscope Management",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, unique=True, verbose_name="Name"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Content Management",
                "ordering": ("id",),
            },
        ),
    ]
