# Generated by Django 4.2.6 on 2024-11-09 11:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, unique=True, verbose_name="Name"),
                ),
                (
                    "designation",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Designation"
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Home Service Management",
                "ordering": ("id",),
            },
        ),
    ]
