# Generated by Django 4.2.6 on 2025-05-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_testimonials"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, unique=True, verbose_name="Name"),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "US Stock",
                "ordering": ("id",),
            },
        ),
        migrations.AlterModelOptions(
            name="testimonials",
            options={
                "ordering": ("id",),
                "verbose_name_plural": "Testimonials Management",
            },
        ),
    ]
