# Generated by Django 4.2.6 on 2025-07-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Change_IN_OI_Increasing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tradingsymbol", models.CharField(max_length=40)),
                ("previous_close", models.FloatField()),
                ("current_price", models.FloatField()),
                ("change_in_price", models.FloatField()),
                ("change_in_price_percentage", models.FloatField()),
                ("prev_oi", models.FloatField()),
                ("oi", models.FloatField()),
                ("change_in_oi", models.FloatField()),
                ("change_in_oi_percentage", models.FloatField()),
                (
                    "created_at",
                    models.CharField(default="2025-07-22 17:33", max_length=20),
                ),
            ],
            options={
                "verbose_name_plural": "Change in OI Increasing Stocks",
                "ordering": ["change_in_oi_percentage"],
            },
        ),
        migrations.CreateModel(
            name="CronJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "function_path",
                    models.CharField(
                        help_text="e.g., trading.cron.my_scheduled_job", max_length=200
                    ),
                ),
                (
                    "cron_schedule",
                    models.CharField(
                        help_text="e.g., */30 * * * * for every 30 minutes",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cron Job",
                "verbose_name_plural": "Cron Jobs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("strategy", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "exchange",
                    models.CharField(
                        choices=[("NSE", "NSE"), ("NFO", "NFO")],
                        default="NSE",
                        max_length=10,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Symbol"
                    ),
                ),
                ("instrument_token", models.CharField(max_length=50)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        default="BUY",
                        max_length=4,
                        verbose_name="T.Type",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "product",
                    models.CharField(
                        choices=[("NRML", "Normal")], default="NRML", max_length=10
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("LIMIT", "Limit"),
                            ("SL", "Stop Loss"),
                            ("SL-M", "Stop Loss Market"),
                        ],
                        default="LIMIT",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "trigger_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETE", "Complete"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("filled_quantity", models.IntegerField(default=0)),
                ("pending_quantity", models.IntegerField(default=0)),
                (
                    "average_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Orders",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScaningStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("total_volume_call", models.FloatField()),
                ("total_volume_put", models.FloatField()),
                ("total_coi_call", models.FloatField()),
                ("total_coi_put", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScaningStockOI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(default="", max_length=10)),
                ("symbol", models.CharField(max_length=10)),
                ("total_volume_call", models.FloatField()),
                ("total_volume_put", models.FloatField()),
                ("total_coi_call", models.FloatField()),
                ("total_coi_put", models.FloatField()),
                (
                    "created_at",
                    models.CharField(default="2025-07-22 17:33", max_length=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scanner_ema",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(max_length=10)),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("ema", models.FloatField()),
                ("ema_type", models.CharField(max_length=10)),
                ("date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CronJobExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("running", "Running"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                ("output", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="trading.cronjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cron Job Execution",
                "verbose_name_plural": "Cron Job Executions",
                "ordering": ["-started_at"],
            },
        ),
    ]
