# Generated by Django 4.2.6 on 2025-07-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="change_in_oi_increasing",
            name="change_in_oi_percentage_quantity",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="change_in_oi_increasing",
            name="change_in_oi_quantity",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="change_in_oi_increasing",
            name="oi_quantity",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="change_in_oi_increasing",
            name="prev_oi_quantity",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-07-23 18:07", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-07-23 18:07", max_length=20),
        ),
    ]
