# Generated by Django 4.2.6 on 2025-07-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "trading",
            "0002_change_in_oi_increasing_change_in_oi_percentage_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="change_in_oi_increasing",
            name="name",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-07-31 20:27", max_length=20),
        ),
        migrations.AlterField(
            model_name="orders",
            name="strategy",
            field=models.CharField(blank=True, default="ATH", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-07-31 20:27", max_length=20),
        ),
    ]
