# Generated by Django 4.2.6 on 2025-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0003_change_in_oi_increasing_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-01 13:07", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-01 13:07", max_length=20),
        ),
    ]
