# Generated by Django 4.2.6 on 2025-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0005_alter_change_in_oi_increasing_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="stoploss",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-01 13:53", max_length=20),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETE", "Complete"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                    ("OPEN", "Open"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-01 13:53", max_length=20),
        ),
    ]
