# Generated by Django 4.2.6 on 2025-08-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0006_orders_stoploss_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdersDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("broker_order_id", models.CharField(max_length=10, null=True)),
                (
                    "strategy",
                    models.CharField(
                        blank=True, default="ATH", max_length=50, null=True
                    ),
                ),
                ("exchange", models.CharField(max_length=10, null=True)),
                (
                    "symbol",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Symbol"
                    ),
                ),
                (
                    "instrument_token",
                    models.CharField(max_length=50, verbose_name="Ins-Token"),
                ),
                (
                    "transaction_type",
                    models.CharField(max_length=4, null=True, verbose_name="T.Type"),
                ),
                ("quantity", models.IntegerField()),
                (
                    "product",
                    models.CharField(
                        choices=[("NRML", "Normal")], default="NRML", max_length=10
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("LIMIT", "Limit"),
                            ("SL", "Stop Loss"),
                            ("SL-M", "Stop Loss Market"),
                        ],
                        default="LIMIT",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stoploss_type",
                    models.BooleanField(
                        choices=[(True, "Manual"), (False, "Automatic")], default=True
                    ),
                ),
                (
                    "stoploss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "trigger_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETE", "Complete"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("filled_quantity", models.IntegerField(default=0)),
                ("pending_quantity", models.IntegerField(default=0)),
                (
                    "average_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("response", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Orders Details",
                "verbose_name_plural": "Orders Details",
                "db_table": "orders_details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-01 17:42", max_length=20),
        ),
        migrations.AlterField(
            model_name="orders",
            name="instrument_token",
            field=models.CharField(max_length=50, verbose_name="Ins-Token"),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-01 17:42", max_length=20),
        ),
    ]
