# Generated by Django 4.2.6 on 2025-08-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0007_ordersdetail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-01 17:43", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-01 17:43", max_length=20),
        ),
    ]
