# Generated by Django 4.2.6 on 2025-08-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0008_alter_change_in_oi_increasing_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordersdetail",
            name="order_id",
        ),
        migrations.AddField(
            model_name="ordersdetail",
            name="order",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_details",
                to="trading.orders",
                verbose_name="Order ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-01 19:19", max_length=20),
        ),
        migrations.AlterField(
            model_name="ordersdetail",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-01 19:19", max_length=20),
        ),
    ]
