# Generated by Django 4.2.6 on 2025-08-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0009_remove_ordersdetail_order_id_ordersdetail_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-02 11:30", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-02 11:30", max_length=20),
        ),
    ]
