# Generated by Django 4.2.6 on 2025-08-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0012_alter_change_in_oi_increasing_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-03 09:21", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-03 09:21", max_length=20),
        ),
    ]
