# Generated by Django 4.2.6 on 2025-08-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0017_alter_change_in_oi_increasing_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="parent_symbol",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="parent_token",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-20 21:03", max_length=20),
        ),
        migrations.AlterField(
            model_name="orders",
            name="filled_quantity",
            field=models.IntegerField(default=0, verbose_name="Fill Qty"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="pending_quantity",
            field=models.IntegerField(default=0, verbose_name="Pending Qty"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="quantity",
            field=models.IntegerField(verbose_name="Qty"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETE", "Complete"),
                    ("OPEN", "Open"),
                    ("CLOSE", "Close"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                    ("OPEN", "Open"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ordersdetail",
            name="broker_order_id",
            field=models.CharField(
                help_text="Broker order Id",
                max_length=30,
                null=True,
                verbose_name="B.OrdID",
            ),
        ),
        migrations.AlterField(
            model_name="ordersdetail",
            name="exchange",
            field=models.CharField(help_text="NSE or NFO", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="ordersdetail",
            name="instrument_token",
            field=models.CharField(
                help_text="Unique Instrument Token", max_length=50, verbose_name="Token"
            ),
        ),
        migrations.AlterField(
            model_name="ordersdetail",
            name="product",
            field=models.CharField(
                choices=[("NRML", "Normal"), ("MIS", "MIS"), ("CNC", "CNC")],
                default="NRML",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ordersdetail",
            name="quantity",
            field=models.IntegerField(verbose_name="QTY"),
        ),
        migrations.AlterField(
            model_name="ordersdetail",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETE", "Complete"),
                    ("OPEN", "Open"),
                    ("CLOSE", "Close"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ordersdetail",
            name="stoploss_type",
            field=models.BooleanField(
                choices=[(True, "Manual"), (False, "Automatic")],
                default=True,
                verbose_name="St.Type",
            ),
        ),
        migrations.AlterField(
            model_name="ordersdetail",
            name="symbol",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ordersdetail",
            name="trigger_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Target",
            ),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-20 21:03", max_length=20),
        ),
    ]
