# Generated by Django 4.2.6 on 2025-08-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0018_orders_parent_symbol_orders_parent_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreMarketStock",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(max_length=50, unique=True)),
                ("last_price", models.FloatField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("change", models.FloatField()),
                ("change_percentage", models.FloatField()),
                ("volume", models.FloatField()),
                ("oi", models.FloatField()),
                ("buy_quantity", models.FloatField()),
                ("sell_quantity", models.FloatField()),
                ("total_traded_value", models.FloatField()),
                ("previous_close", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Pre-Market Stocks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-21 20:33", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-21 20:33", max_length=20),
        ),
    ]
