# Generated by Django 4.2.6 on 2025-08-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0019_premarketstock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="premarketstock",
            name="type",
            field=models.CharField(
                choices=[("PRE", "pre"), ("CLOSE", "close")],
                default="PRE",
                help_text="Type of pre-market data",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-21 20:37", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-21 20:37", max_length=20),
        ),
    ]
