# Generated by Django 4.2.6 on 2025-08-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0020_premarketstock_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-21 21:03", max_length=20),
        ),
        migrations.AlterField(
            model_name="premarketstock",
            name="buy_quantity",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="premarketstock",
            name="previous_close",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="premarketstock",
            name="sell_quantity",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="premarketstock",
            name="total_traded_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="premarketstock",
            name="type",
            field=models.CharField(
                choices=[
                    ("PRE-MARKET", "pre-market"),
                    ("POST-MARKET", "post-market"),
                    ("MARKET", "market"),
                ],
                default="PRE-MARKET",
                help_text="Type of pre-market data",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-21 21:03", max_length=20),
        ),
    ]
