# Generated by Django 4.2.6 on 2025-08-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0021_alter_change_in_oi_increasing_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-21 21:16", max_length=20),
        ),
        migrations.AlterField(
            model_name="premarketstock",
            name="symbol",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-21 21:16", max_length=20),
        ),
    ]
