# Generated by Django 4.2.6 on 2025-08-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0022_alter_change_in_oi_increasing_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="COI",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(default="", max_length=50)),
                ("instrument_token", models.CharField(default="", max_length=50)),
                ("expiry_date", models.DateField()),
                ("strike", models.FloatField(default=0)),
                ("call_oi", models.FloatField(default=0)),
                ("call_coi", models.FloatField(default=0)),
                ("call_coi_percentage", models.FloatField(default=0)),
                ("call_volume", models.FloatField(default=0)),
                ("call_last_price", models.FloatField(default=0)),
                ("call_lots", models.FloatField(default=0)),
                ("call_pre_oi", models.FloatField(default=0)),
                ("call_current_price", models.FloatField(default=0)),
                ("put_oi", models.FloatField(default=0)),
                ("put_coi", models.FloatField(default=0)),
                ("put_coi_percentage", models.FloatField(default=0)),
                ("put_volume", models.FloatField(default=0)),
                ("put_last_price", models.FloatField(default=0)),
                ("put_lots", models.FloatField(default=0)),
                ("put_pre_oi", models.FloatField(default=0)),
                ("put_current_price", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "COI",
                "db_table": "coi_data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-25 21:38", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-25 21:38", max_length=20),
        ),
    ]
