# Generated by Django 4.2.6 on 2025-08-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0023_coi_alter_change_in_oi_increasing_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coi",
            name="call_instrument_token",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="coi",
            name="call_trading_symbol",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="coi",
            name="put_instrument_token",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="coi",
            name="put_trading_symbol",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-25 22:57", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-25 22:57", max_length=20),
        ),
    ]
