# Generated by Django 4.2.6 on 2025-08-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0024_coi_call_instrument_token_coi_call_trading_symbol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coi",
            name="current_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-26 20:11", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-26 20:11", max_length=20),
        ),
    ]
