# Generated by Django 4.2.6 on 2025-08-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0025_coi_current_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coi",
            name="call_day_high",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="coi",
            name="call_day_low",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="coi",
            name="put_day_high",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="coi",
            name="put_day_low",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-28 11:10", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-28 11:10", max_length=20),
        ),
    ]
