# Generated by Django 4.2.6 on 2025-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "trading",
            "0026_coi_call_day_high_coi_call_day_low_coi_put_day_high_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coi",
            name="call_day_open",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="coi",
            name="put_day_open",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-08-28 12:12", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-08-28 12:12", max_length=20),
        ),
    ]
