# Generated by Django 4.2.6 on 2025-09-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0027_coi_call_day_open_coi_put_day_open_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-09-03 08:21", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-09-03 08:21", max_length=20),
        ),
    ]
