# Generated by Django 4.2.6 on 2025-09-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0028_alter_change_in_oi_increasing_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-09-04 17:12", max_length=20),
        ),
        migrations.AlterField(
            model_name="coi",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="coi",
            name="symbol",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-09-04 17:12", max_length=20),
        ),
    ]
