# Generated by Django 4.2.6 on 2025-10-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0029_alter_change_in_oi_increasing_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MostActiveSymbol",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CAll", "call"),
                            ("PUT", "put"),
                            ("FAVORITE", "favorite"),
                            ("HATE", "Hate"),
                            ("LOVELY", "lovely"),
                        ],
                        default="CAll",
                        help_text="Type of most active data",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Most Active Symbols",
                "db_table": "most_active_symbol",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-10-20 08:08", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-10-20 08:08", max_length=20),
        ),
    ]
