# Generated by Django 4.2.6 on 2025-11-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0030_mostactivesymbol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="symbol_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="use_parent_symbol",
            field=models.CharField(default=1, max_length=1, verbose_name="Ins-Token"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-11-17 14:18", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-11-17 14:18", max_length=20),
        ),
    ]
