# Generated by Django 4.2.6 on 2025-11-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0031_orders_symbol_price_orders_use_parent_symbol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-11-17 14:22", max_length=20),
        ),
        migrations.AlterField(
            model_name="orders",
            name="use_parent_symbol",
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-11-17 14:22", max_length=20),
        ),
    ]
