# Generated by Django 4.2.6 on 2025-11-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0032_alter_change_in_oi_increasing_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersdetail",
            name="parent_symbol",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ordersdetail",
            name="parent_token",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ordersdetail",
            name="symbol_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-11-17 21:07", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-11-17 21:07", max_length=20),
        ),
    ]
