# Generated by Django 4.2.6 on 2025-11-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "trading",
            "0033_ordersdetail_parent_symbol_ordersdetail_parent_token_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="option_type",
            field=models.CharField(default="CE", max_length=2),
        ),
        migrations.AddField(
            model_name="ordersdetail",
            name="option_type",
            field=models.CharField(default="CE", max_length=2),
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2025-11-18 08:35", max_length=20),
        ),
        migrations.AlterField(
            model_name="ordersdetail",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="B. Price",
            ),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.CharField(default="2025-11-18 08:35", max_length=20),
        ),
    ]
