# Generated by Django 4.2.6 on 2026-01-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0034_orders_option_type_ordersdetail_option_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2026-01-30 17:53", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
