# Generated by Django 4.2.6 on 2026-01-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0035_alter_change_in_oi_increasing_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scaningstockoi",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2026-01-30 18:02", max_length=20),
        ),
    ]
