# Generated by Django 4.2.6 on 2026-01-30 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0036_remove_scaningstockoi_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
