# Generated by Django 4.2.6 on 2026-01-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0037_scaningstockoi_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2026-01-30 18:05", max_length=20),
        ),
        migrations.AlterField(
            model_name="scaningstockoi",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
