# Generated by Django 4.2.6 on 2026-02-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0038_alter_change_in_oi_increasing_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change_in_oi_increasing",
            name="created_at",
            field=models.CharField(default="2026-02-07 09:15", max_length=20),
        ),
    ]
