# Generated by Django 4.2.6 on 2026-02-07 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0042_alter_change_in_oi_increasing_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="change_in_oi_increasing",
            name="created_at",
        ),
    ]
