# Generated by Django 4.2.6 on 2026-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0043_remove_change_in_oi_increasing_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="COI_INDEX",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, default="", max_length=50)),
                ("instrument_token", models.CharField(default="", max_length=50)),
                ("expiry_date", models.DateField()),
                ("strike", models.FloatField(default=0)),
                ("current_price", models.FloatField(default=0)),
                ("call_trading_symbol", models.CharField(default="", max_length=50)),
                ("call_instrument_token", models.CharField(default="", max_length=50)),
                ("call_oi", models.FloatField(default=0)),
                ("call_coi", models.FloatField(default=0)),
                ("call_coi_percentage", models.FloatField(default=0)),
                ("call_volume", models.FloatField(default=0)),
                ("call_last_price", models.FloatField(default=0)),
                ("call_lots", models.FloatField(default=0)),
                ("call_pre_oi", models.FloatField(default=0)),
                ("call_current_price", models.FloatField(default=0)),
                ("call_day_low", models.FloatField(default=0)),
                ("call_day_high", models.FloatField(default=0)),
                ("call_day_open", models.FloatField(default=0)),
                ("put_trading_symbol", models.CharField(default="", max_length=50)),
                ("put_instrument_token", models.CharField(default="", max_length=50)),
                ("put_oi", models.FloatField(default=0)),
                ("put_coi", models.FloatField(default=0)),
                ("put_coi_percentage", models.FloatField(default=0)),
                ("put_volume", models.FloatField(default=0)),
                ("put_last_price", models.FloatField(default=0)),
                ("put_lots", models.FloatField(default=0)),
                ("put_pre_oi", models.FloatField(default=0)),
                ("put_current_price", models.FloatField(default=0)),
                ("put_day_low", models.FloatField(default=0)),
                ("put_day_high", models.FloatField(default=0)),
                ("put_day_open", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "COI INDEX",
                "db_table": "coi_data_index",
                "ordering": ["-created_at"],
            },
        ),
    ]
