# Generated by Django 4.2.6 on 2026-06-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0044_coi_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nifty_notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, default="", max_length=50)),
                ("expiry_date", models.DateField()),
                ("strike", models.FloatField(default=0)),
                ("call_coi", models.FloatField(default=0)),
                ("put_coi", models.FloatField(default=0)),
                ("message", models.TextField(default="")),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "Nifty Notification",
                "db_table": "noifty_notification",
                "ordering": ["-created_at"],
            },
        ),
    ]
