# Generated by Django 4.2.6 on 2026-06-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0045_nifty_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="nifty_notification",
            name="signal",
            field=models.CharField(default="", max_length=20),
        ),
    ]
