# Generated by Django 4.2.6 on 2026-07-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0046_nifty_notification_signal"),
    ]

    operations = [
        migrations.AddField(
            model_name="coi_index",
            name="pcr",
            field=models.FloatField(default=0),
        ),
    ]
