"""
Django settings for astrology project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import pymysql
import os
from datetime import datetime, time, timedelta

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_DIR = os.path.dirname(BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9+@6b5p5j%b+hr4+@gl6*zv5^k^^k6iqzx=0g=91k@5_o*$6@)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


from dotenv import load_dotenv

load_dotenv()
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "website",
    "trading",
    "ZERODHA_API",
    "KOTAK_NEO_API.apps.KOTAKNEOAPIConfig",
    "ckeditor",
    #"zerodha",
    #'django_apscheduler',
    "django_crontab",
    'dal',
    'dal_select2',
    'rest_framework',
    "rest_framework.authtoken",
    #'polls',
    'tradingview'
    

] 
CRONJOBS = [
    # Every 30 minutes
    #('45 06 * * *', 'trading.cron.zerodha_save_changein_oi'), # save previous OI for night
    #('*/1 7-9 * * 1-5', 'trading.cron.zerodha_save_changein_oi'), 
     
    #('*/15 9-15 * * 1-5', 'trading.cron.Change_IN_OI_Increasing_Save'),

    #('*/10 9-15 * * 1-5', 'trading.cron.Change_IN_OI_scanner'),


    ('*/1 9-15 * * 1-5', 'trading.cron_test.zerodha_place_order'),

    #('*/1 9-15 * * 1-5', 'trading.cron_test.OrdersDetailUpdate'),
    ('*/1 9-15 * * 1-5', 'trading.cron_test.OrdersDetailStatusUpdate'),
    #('*/1 9-15 * * 1-5', 'trading.cron_test.crose_high_low'),
    ('*/2 9-15 * * 1-5', 'trading.cron.option_chain'),

    #('*/2 9-15 * * 1-5', 'trading.cron.ThreadExecutor'),
    
    #('*/3 9-15 * * 1-5', 'trading.cron.scanner_200ma'),

    
    # Kotak Neo API Cron Jobs
    # ('*/5 9-15 * * 1-5', 'KOTAK_NEO_API.kotak_neo_cron.kotak_market_data_sync'),
    # ('*/30 9-15 * * 1-5', 'KOTAK_NEO_API.kotak_neo_cron.kotak_holdings_sync'),
    # ('*/2 9-15 * * 1-5', 'KOTAK_NEO_API.kotak_neo_cron.kotak_alert_monitoring'),
    # ('*/15 9-15 * * 1-5', 'KOTAK_NEO_API.kotak_neo_cron.kotak_option_chain_sync'),
    # ('0 */1 * * *', 'KOTAK_NEO_API.kotak_neo_cron.manage_kotak_tokens'),
    # ('0 2 * * *', 'KOTAK_NEO_API.kotak_neo_cron.cleanup_old_market_data'),
    # ('0 6 * * *', 'KOTAK_NEO_API.kotak_neo_cron.sync_kotak_instruments'),
    
    # Every day at 9:30, 10:30, 11:30, 12:30, 13:30, 14:30, 15:30
    #('30 9-15 * * *', 'your_app.cron.my_business_hours_job')

    #('*/1 * * * *', 'trading.cron.my_scheduled_job', '>> dajngo.log 2>&1'),
    #('*/1 * * * *', 'trading.cron.my_scheduled_job2'),
]
CRON_CLASSES = [
    'trading.cron.TestCronJob',
]

# REST_FRAMEWORK = {
#     # Use Django's standard `django.contrib.auth` permissions,
#     # or allow read-only access for unauthenticated users.
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
#     ]
# }
# REST_FRAMEWORK = {
#             'DEFAULT_AUTHENTICATION_CLASSES': [
#                 'rest_framework.authentication.TokenAuthentication',
#                 'rest_framework.authentication.SessionAuthentication', # Optional, for browsable API
#             ],
#         }

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "astrology.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        #"DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'website.header.header',
            ],
        },
    },
]


WSGI_APPLICATION = "astrology.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'astrology',
        'USER': 'root',
        'PASSWORD': '',
        #'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        #'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET time_zone='+00:00'",  # UTC
        }
    }
}
CKEDITOR_CONFIGS = {
    'default': {
        'versionCheck': False
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
#USE_I18N = True
#USE_L10N = True

USE_TZ = False

TIME_ZONE = "Asia/Kolkata"




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_ROOT = '/static/'
STATIC_URL = '/static/'



STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# APScheduler settings
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds
SCHEDULER_DEFAULT = True

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            #'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'format': '{levelname} {asctime} {module} {funcName} : {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'cron.log'),
            'formatter': 'verbose',
        },
        'trading_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'trading.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'trading': {
            'handlers': ['console', 'trading_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'trading.cron': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
TODAY_DATE = datetime.now().date()-timedelta(days=1)
#TODAY_DATE = "2026-05-15"
print(TODAY_DATE)
#EXPIRY = '2026-04-28'
EXPIRY = '2026-05-26'
# ZERODHA_API_KEY = 'wx9fzilixlw1ihob'
# ZERODHA_API_SECRET = 'ix2u1lc5pdgxma9mgfflfg16nmma8osp'
# ZERODHA_ACCESS_TOKEN = ''

KOTAK_NEO_USER_ID = 'client26349'
KOTAK_NEO_API_KEY = 'L3oHgffw2uTUcyIvAiPhvjJlVWUa'
KOTAK_NEO_API_SECRET = 'VOmGP3ofzWSBzmeAOFSgJXL1SVYa'



