# Generated by Django 4.2.6 on 2025-08-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KotakNeoInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument_token",
                    models.CharField(
                        help_text="Unique instrument token", max_length=50, unique=True
                    ),
                ),
                (
                    "tradingsymbol",
                    models.CharField(help_text="Trading symbol", max_length=50),
                ),
                ("name", models.CharField(help_text="Instrument name", max_length=100)),
                (
                    "exchange",
                    models.CharField(
                        help_text="Exchange (NSE, NFO, etc.)", max_length=10
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("EQ", "Equity"),
                            ("FUT", "Future"),
                            ("OPT", "Option"),
                            ("CE", "Call Option"),
                            ("PE", "Put Option"),
                            ("INDEX", "Index"),
                        ],
                        help_text="Type of instrument",
                        max_length=10,
                    ),
                ),
                (
                    "segment",
                    models.CharField(help_text="Market segment", max_length=20),
                ),
                (
                    "expiry",
                    models.DateField(
                        blank=True, help_text="Expiry date for derivatives", null=True
                    ),
                ),
                (
                    "strike_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Strike price for options",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("lot_size", models.IntegerField(default=1, help_text="Lot size")),
                (
                    "tick_size",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.05,
                        help_text="Tick size",
                        max_digits=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether instrument is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kotak Neo Instrument",
                "verbose_name_plural": "Kotak Neo Instruments",
                "ordering": ["tradingsymbol"],
            },
        ),
        migrations.CreateModel(
            name="KotakNeoUserToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        help_text="Kotak Neo User ID", max_length=50, unique=True
                    ),
                ),
                (
                    "access_token",
                    models.TextField(help_text="Access token for API authentication"),
                ),
                (
                    "refresh_token",
                    models.TextField(help_text="Refresh token for token renewal"),
                ),
                ("token_type", models.CharField(default="Bearer", max_length=20)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Token expiration timestamp"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("invalid", "Invalid"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kotak Neo User Token",
                "verbose_name_plural": "Kotak Neo User Tokens",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KotakNeoOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        help_text="Kotak Neo order ID", max_length=50, unique=True
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        help_text="Buy or Sell",
                        max_length=4,
                    ),
                ),
                ("quantity", models.IntegerField(help_text="Order quantity")),
                (
                    "product",
                    models.CharField(
                        choices=[("NRML", "Normal"), ("MIS", "MIS"), ("CNC", "CNC")],
                        default="NRML",
                        help_text="Product type",
                        max_length=10,
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("LIMIT", "Limit"),
                            ("SL", "Stop Loss"),
                            ("SL-M", "Stop Loss Market"),
                        ],
                        default="LIMIT",
                        help_text="Order variant",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Order price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "trigger_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Trigger price for SL orders",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETE", "Complete"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("OPEN", "Open"),
                        ],
                        default="PENDING",
                        help_text="Order status",
                        max_length=20,
                    ),
                ),
                (
                    "filled_quantity",
                    models.IntegerField(default=0, help_text="Filled quantity"),
                ),
                (
                    "pending_quantity",
                    models.IntegerField(default=0, help_text="Pending quantity"),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average fill price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "order_timestamp",
                    models.DateTimeField(help_text="Order timestamp from broker"),
                ),
                (
                    "exchange_timestamp",
                    models.DateTimeField(
                        blank=True, help_text="Exchange timestamp", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if order failed", null=True
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        default=dict, help_text="Full response from Kotak Neo API"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="KOTAK_NEO_API.kotakneoinstrument",
                    ),
                ),
                (
                    "user_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="KOTAK_NEO_API.kotakneousertoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kotak Neo Order",
                "verbose_name_plural": "Kotak Neo Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KotakNeoOptionChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(help_text="Underlying symbol", max_length=20),
                ),
                ("expiry_date", models.DateField(help_text="Expiry date")),
                (
                    "strike_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Strike price", max_digits=10
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[("CE", "Call"), ("PE", "Put")],
                        help_text="Call or Put",
                        max_length=2,
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("open_interest", models.BigIntegerField(blank=True, null=True)),
                ("change_in_oi", models.BigIntegerField(blank=True, null=True)),
                (
                    "implied_volatility",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "delta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "gamma",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "theta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "vega",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "bid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("bid_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "ask_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("ask_quantity", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kotak Neo Option Chain",
                "verbose_name_plural": "Kotak Neo Option Chains",
                "ordering": ["symbol", "strike_price", "option_type"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "expiry_date"],
                        name="KOTAK_NEO_A_symbol_bad74b_idx",
                    )
                ],
                "unique_together": {
                    ("symbol", "expiry_date", "strike_price", "option_type")
                },
            },
        ),
        migrations.CreateModel(
            name="KotakNeoAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Alert name", max_length=100)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("PRICE", "Price Alert"),
                            ("VOLUME", "Volume Alert"),
                            ("OI", "Open Interest Alert"),
                            ("CUSTOM", "Custom Alert"),
                        ],
                        help_text="Type of alert",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("ABOVE", "Above"),
                            ("BELOW", "Below"),
                            ("EQUALS", "Equals"),
                            ("CROSSES_ABOVE", "Crosses Above"),
                            ("CROSSES_BELOW", "Crosses Below"),
                        ],
                        help_text="Alert condition",
                        max_length=20,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target value for alert",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRIGGERED", "Triggered"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        help_text="Alert status",
                        max_length=20,
                    ),
                ),
                (
                    "is_repeatable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether alert can be triggered multiple times",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        blank=True, help_text="When alert was triggered", null=True
                    ),
                ),
                (
                    "triggered_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Value when triggered",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Alert description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="KOTAK_NEO_API.kotakneoinstrument",
                    ),
                ),
                (
                    "user_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="KOTAK_NEO_API.kotakneousertoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kotak Neo Alert",
                "verbose_name_plural": "Kotak Neo Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KotakNeoMarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, help_text="Data timestamp"),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bid_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("bid_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "ask_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("ask_quantity", models.IntegerField(blank=True, null=True)),
                ("open_interest", models.BigIntegerField(blank=True, null=True)),
                (
                    "implied_volatility",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        default=dict, help_text="Raw market data from API"
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_data",
                        to="KOTAK_NEO_API.kotakneoinstrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kotak Neo Market Data",
                "verbose_name_plural": "Kotak Neo Market Data",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["instrument", "-timestamp"],
                        name="KOTAK_NEO_A_instrum_10cebf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="KotakNeoHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(help_text="Holding quantity")),
                (
                    "average_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average purchase price",
                        max_digits=10,
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Last traded price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "market_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current market value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Profit/Loss",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "pnl_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="P&L percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        default="NRML", help_text="Product type", max_length=10
                    ),
                ),
                ("exchange", models.CharField(help_text="Exchange", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="KOTAK_NEO_API.kotakneoinstrument",
                    ),
                ),
                (
                    "user_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="KOTAK_NEO_API.kotakneousertoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kotak Neo Holding",
                "verbose_name_plural": "Kotak Neo Holdings",
                "ordering": ["-updated_at"],
                "unique_together": {("user_token", "instrument", "product")},
            },
        ),
        migrations.CreateModel(
            name="KotakNeoAPILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(help_text="API endpoint called", max_length=200),
                ),
                ("method", models.CharField(help_text="HTTP method", max_length=10)),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, help_text="HTTP status code", null=True
                    ),
                ),
                (
                    "response_time",
                    models.DurationField(
                        blank=True, help_text="API response time", null=True
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(default=dict, help_text="Request data sent"),
                ),
                (
                    "response_data",
                    models.JSONField(default=dict, help_text="Response data received"),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("DEBUG", "Debug"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True, help_text="Log message")),
                (
                    "error_details",
                    models.TextField(blank=True, help_text="Error details if any"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_logs",
                        to="KOTAK_NEO_API.kotakneousertoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kotak Neo API Log",
                "verbose_name_plural": "Kotak Neo API Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_token", "-created_at"],
                        name="KOTAK_NEO_A_user_to_e0e7c7_idx",
                    ),
                    models.Index(
                        fields=["log_level", "-created_at"],
                        name="KOTAK_NEO_A_log_lev_f9f8cd_idx",
                    ),
                ],
            },
        ),
    ]
